### ISSUE TITLE
Webpack-dev-server newer version issue.

### ISSUE THREAD

**Issue by Stoneleee** [Stoneleee/online-shop#3]
When upgrade 
`webpack-dev-server` ^2.9.1 -> ^3.1.11,
`webpack-bundle-analyzer` ^2.9.0 -> ^3.3.2

I got the issue below:
```
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- D:\Stone_practice\online-shop\node_modules\webpack-dev-server\bin\webpack-dev-server.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Stone_practice\online-shop\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {

  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Stone_practice\\online-shop\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! online-shop@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the online-shop@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-03-25T07_29_23_735Z-debug.log
error Command failed with exit code 1.
```

**Comment by Stoneleee** [comment]
fixed by rebacking version to 2.9.*,above two dependencie
